language: erlang

install:
   - cd ~/
   - git clone -b pharo1.3 git://github.com/dalehenrich/filetree.git
   - git clone git://github.com/dalehenrich/monticello-work.git
   - cd ~/builder/images
   - wget https://gforge.inria.fr/frs/download.php/30567/PharoCore-1.3-13328.zip
   - unzip PharoCore-1.3-13328.zip
   - cd PharoCore-1.3
   - mv *.sources ~/builder/sources
   - mv *.changes ..
   - mv *.image ..
   - cd ~/builder

script:
   - ./build.sh -i PharoCore-1.3 -s travisCI.st -o travisCI
   - cd ~/builder/builds/travisCI/
   - if ( test -e PharoDebug.log ); then cat PharoDebug.log; fi
 
