# NOTE - use the file in templates/travis.yml as the starting point for your project's .travis.yml file
#
# Copyright (c) 2012 VMware, Inc. All Rights Reserved <dhenrich@vmware.com>.
#

language: erlang

env:
#   - ST=PharoCore-1.0  # pharo 1.0 needs a different VM
   - ST=PharoCore-1.1
   - ST=PharoCore-1.2
   - ST=PharoCore-1.3
   - ST=Pharo-1.4
#   - ST=Pharo-2.0 #Pharo-2.0 has trouble loading Metacello (FileTree issues)
#   - ST=Squeak4.3 # ensure that obsolete platform name Squeak4.3 works
   - ST=Squeak-4.3
   - ST=Squeak-4.4

install:
   - source build_env_vars
   - ./build_image.sh

script: ./testTravisCI.sh

script: ./testBuilderCI.sh

