language: erlang

# build matrix: "PharoCore-1.3" or "Squeak4.3" ... parallel tests for
#   all listed environments
env:
   - ST=PharoCore-1.3

install:
   - BASE_PATH="$(pwd)"
   - BUILD_PATH="${WORKSPACE:=$BASE_PATH/builds}"
   - IMAGES_PATH="$BASE_PATH/images"
   - SCRIPTS_PATH="$BASE_PATH/scripts"
   - SOURCES_PATH="$BASE_PATH/sources"
   - VM_PATH="$BASE_PATH/oneclick/Contents"
   - BUILD_CACHE="$BASE_PATH/cache"
   - echo $HOME
   - echo $BASE_PATH
   - cd $BASE_PATH
   - git clone -b pharo1.3 git://github.com/dalehenrich/filetree.git
   - git clone git://github.com/dalehenrich/metacello-work.git
   - ./build_image.sh
   - cd ~/builds/dalehenrich/builderCI

script:
   - ./build.sh -i PharoCore-1.3 -s travisCI -o travisCI
   - cd ~/builds/dalehenrich/builderCI/builds/travisCI/
   - if ( test -e PharoDebug.log ); then cat PharoDebug.log; fi
   - if ( test -e PharoDebug.log ); then lksdf; fi

