language: erlang

# build matrix: "PharoCore-1.3" or "Squeak4.3" ... parallel tests for
#   all listed environments
env:
   - ST=PharoCore-1.3

install:
   - source build_env_vars
   - ./build_clone.sh -g "-b pharo1.3 git://github.com/dalehenrich/filetree.git"
   - ./build_clone.sh -g "git://github.com/dalehenrich/metacello-work.git"
   - ./build_image.sh

script:
   - ./build.sh -i PharoCore-1.3 -m -f "$BUILDER_CI_HOME/tests/travisCI.st" -o travisCI
   - cd "${BUILD_PATH}/travisCI/"
   - if ( test -e PharoDebug.log ); then cat PharoDebug.log; fi
   - if ( test -e PharoDebug.log ); then die; fi
   - if ( test -e TravisCISuccess.txt ); then cat TravisCISuccess.txt; fi
   - if ( test -e TravisCIFailure.txt ); then cat TravisCIFailure.txt; fi
   - if ( test -e TravisCIFailure.txt ); then die; fi
