# NOTE - use the file in templates/travis.yml as the starting point for your project's .travis.yml file
#
# Copyright (c) 2012 VMware, Inc. All Rights Reserved <dhenrich@vmware.com>.
#

language: erlang

env:
   - ST=PharoCore-1.0
   - ST=PharoCore-1.1.2
   - ST=PharoCore-1.2.2
#   - ST=PharoCore-1.3
#   - ST=Pharo-1.4
#   - ST=Pharo-2.0 #Pharo-2.0 has trouble loading Metacello (FileTree issues)
#   - ST=Squeak4.3 # ensure that obsolete platform name Squeak4.3 works
#   - ST=Squeak-4.3
#   - ST=Squeak-4.4

install:
   - source build_env_vars
   - ./build_image.sh

script:
#   - ./build.sh -i $ST -s latAmMirror.st -m -f "$BUILDER_CI_HOME/tests/travisCI.st" -o travisCI
   - ./build.sh -i $ST -m -f "$BUILDER_CI_HOME/tests/travisCI.st" -o travisCI
   - cd "${BUILD_PATH}/travisCI/"
   - ls -altr *
   - $BUILDER_CI_HOME/buildImageErrorCheck.sh
   - $BUILDER_CI_HOME/buildTravisStatusCheck.sh
   - cat TravisTranscript.txt
   - cd $BUILDER_CI_HOME
#   - ./build.sh -i $ST -s latAmMirror.st -X -f "$BUILDER_CI_HOME/tests/skipMetacelloBootstrap.st" -o travisCI
   - ./build.sh -i $ST -X -f "$BUILDER_CI_HOME/tests/skipMetacelloBootstrap.st" -o travisCI
   - cd "${BUILD_PATH}/travisCI/"
   - ls -altr *
   - $BUILDER_CI_HOME/buildImageErrorCheck.sh
   - $BUILDER_CI_HOME/buildTravisStatusCheck.sh
   - cat TravisTranscript.txt

