# NOTE - use the file in templates/travis.yml as the starting point for your project's .travis.yml file
#
# Copyright (c) 2012 VMware, Inc. All Rights Reserved <dhenrich@vmware.com>.
# Copyright (C) 2014 GemTalk Systems LLC <dale.henrichs@gemtalksystems.com>
#

language: erlang

env:

   # - ST=Pharo-1.4
   # - ST=Pharo-2.0 
   - ST=Squeak-4.5
   # - ST=GemStone-3.2.0

   # - ST=PharoCore-1.1
   # - ST=PharoCore-1.2
   # - ST=PharoCore-1.3
   # - ST=Pharo-3.0
   # - ST=Squeak-4.3
   # - ST=Squeak-4.4
   # - ST=Squeak-Trunk
   # - ST=GemStone-2.4.4.1
   # - ST=GemStone-2.4.4.7
   # - ST=GemStone-2.4.5
   # - ST=GemStone-2.4.5.2
   # - ST=GemStone-3.0.1
   # - ST=GemStone-3.1.0.2
   # - ST=GemStone-3.1.0.4
   # - ST=GemStone-3.1.0.5
   # - ST=GemStone-3.1.0.6

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
   - export PROJECT_HOME="$(pwd)"
   - source build_env_vars
   - ./build_image.sh

# use -verbose flag to control whether or not transcript is dumped
# to travis log
script: ./testBuilderCI.sh  -verbose
