language: erlang

install:
   - cd ~/
   - git clone -b pharo1.3 git://github.com/dalehenrich/filetree.git
   - git clone git://github.com/dalehenrich/metacello-work.git
   - cd ~/builds/dalehenrich/builderCI/images
   - wget https://gforge.inria.fr/frs/download.php/30567/PharoCore-1.3-13328.zip
   - unzip PharoCore-1.3-13328.zip
   - cd PharoCore-1.3
   - mv *.sources ~/builds/dalehenrich/builderCI/sources
   - mv *.changes ..
   - mv *.image ..
   - cd ~/builds/dalehenrich/builderCI

script:
   - ./build.sh -i PharoCore-1.3 -s travisCI -o travisCI
   - cd ~/builds/dalehenrich/builderCI/travisCI/
   - if ( test -e PharoDebug.log ); then cat PharoDebug.log; fi

