# NOTE - use the file in templates/travis.yml as the starting point for your project's .travis.yml file
#
# Copyright (c) 2012 VMware, Inc. All Rights Reserved <dhenrich@vmware.com>.
#

language: erlang

env:
#   - ST=PharoCore-1.0  # pharo 1.0 needs a different VM
   - ST=PharoCore-1.1
   - ST=PharoCore-1.2
   - ST=PharoCore-1.3
   - ST=Pharo-1.4
#   - ST=Pharo-2.0 #Pharo-2.0 has trouble loading Metacello (FileTree issues)
   - ST=Squeak-4.3
   - ST=Squeak-4.4
   - ST=Squeak-4.5
   - ST=GemStone-2.4.4.1
   - ST=GemStone-2.4.4.7
   - ST=GemStone-2.4.5
   - ST=GemStone-2.4.5.1
   - ST=GemStone-3.0.1
   - ST=GemStone-3.1.0.2

install:
   - export PROJECT_HOME="$(pwd)"
   - source build_env_vars
   - ./build_image.sh

script: ./testBuilderCI.sh

